# @package _global_
model:
  name: logistic-regression # (str): Model name
  require_imputation: True # (bool): Whether the model requires imputation.
  args: # https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
    dual: False
    tol: 0.0001
    C: 1.0
    fit_intercept: True
    intercept_scaling: True
    class_weight: Null
    random_state: ${project.seed}
    penalty_solver: "l2_lbfgs" # custom argument is split into penalty and solver
    max_iter: 100
    l1_ratio: 0.5

# Parameters that will only take effect if running with --multirun
hydra:
  sweeper:
    params:
      ++model.args.penalty_solver: choice("elasticnet_saga")
      ++model.args.C: interval(1e-5, 1.0)
      ++model.args.l1_ratio: interval(1e-5, 1.0)
      # preprocessing
      ++preprocessing.post_split.scaling: choice("null", "z-score-normalization")
